name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup python with dev dependencies
        uses: ./.github/actions/deps
        with:
          python-version: ${{ matrix.python-version }}
      - run: flake8 .
      - run: mypy .
      - run: PYTHONPATH=. pytest --cov --cov-report=term-missing

  release:
    needs:
      - tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python with dev dependencies
        uses: ./.github/actions/deps
        with:
          python-version: '3.10'
      - run: pip install build twine pdm-pep517
      - run: python -m build -n
      - run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
